[package]
name = "celestus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "celestus"
path = "src/bin/main.rs"

[lib]
name = "celestus"
path = "src/lib/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
thiserror = "1.0.37"
diesel = { version = "2.0.2", features = ["postgres", "uuid", "chrono", "r2d2", "serde_json"] }
dotenvy = "0.15.5"
actix-web = "4.2.1"
uuid = { version = "1.2.1", features = ["v4", "serde"] }
serde = { version = "^1", features = ["derive"] }
serde_derive = "1.0.145"
serde_json = "1.0.86"
env_logger = "0.9.1"
log = "0.4.17"
chrono = "0.4.22"
jsonwebtoken = "8.1.1"