services:
    postgres:
        build:
            context: ../db/postgres
            args:
                DOCKER_BUILDKIT: 1
            dockerfile: Dockerfile
            target: prod
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        restart: always
        profiles:
            - prod

    postgres-dev:
        build:
            context: ../db/postgres
            args:
                DOCKER_BUILDKIT: 1
            dockerfile: Dockerfile
            target: dev
        image: postgres-dev
        container_name: postgres-dev
        ports:
            - 5433:5433
        volumes:
            - postgres-dev:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=123456
        restart: always
        command: -p 5433
        profiles:
            - dev
