services:
    vault:
        build:
            context: ../configs/secrets/vault
            args:
                DOCKER_BUILDKIT: 1
            dockerfile: Dockerfile
            target: prod
        image: celestus-vault
        container_name: celestus-vault
        ports:
            - 8200:8200
        volumes:
            - vault-data:/vault/data
        environment:
            - VAULT_ADDR=http://0.0.0.0:8200
            - VAULT_API_ADDR=http://0.0.0.0:8200
        command: server -config=/vault/config/vault-config.json
        restart: always
        cap_add:
            - IPC_LOCK
        profiles:
            - prod

    vault-dev:
        build:
            context: ../configs/secrets/vault
            args:
                DOCKER_BUILDKIT: 1
            dockerfile: Dockerfile
            target: dev
        image: vault-dev
        container_name: vault-dev
        # ports:
        #     - 8201:8201
        volumes:
            - ../configs/secrets/vault/vault-root-token:/vault/data/vault-root-token
            - vault-data-dev:/vault/data
        environment:
            - VAULT_ADDR=http://0.0.0.0:8201
            - VAULT_API_ADDR=http://0.0.0.0:8201
            - DEV_VAULT_TOKEN=test-dev
        command: server -config=/vault/config/vault-config-dev.json
        restart: always
        cap_add:
            - IPC_LOCK
        profiles:
            - dev

    # consul:
    #   build:
    #     context: ./configs/secrets/consul
    #     dockerfile: Dockerfile
    #   ports:
    #     - 8500:8500
    #   command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    #   volumes:
    #     - ./configs/secrets/consul/config/consul-config.json:/consul/config/config.json
    #     - ./configs/secrets/consul/data:/consul/data
