-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE IF NOT EXISTS public.roles (
    id uuid NOT NULL,
    name character varying NOT NULL,
    description character varying,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    config jsonb NOT NULL,
    role_group_id uuid,
    PRIMARY KEY (id),
    CONSTRAINT unique_role_name UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    email_address character varying NOT NULL,
    phone character varying,
    external_provider_config jsonb,
    config jsonb,
    user_group_id uuid,
    role_id uuid,
    PRIMARY KEY (id),
    CONSTRAINT unique_email_address UNIQUE (email_address)
);
CREATE TABLE IF NOT EXISTS public.role_groups (
    id uuid NOT NULL,
    name character varying NOT NULL,
    description character varying,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    config jsonb NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_role_group_name UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS public.user_groups (
    id uuid NOT NULL,
    name character varying NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    description character varying,
    config jsonb NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_user_group_name UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS public.system_configs (
    id uuid NOT NULL,
    name character varying NOT NULL,
    config jsonb NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    PRIMARY KEY (id),
    CONSTRAINT unique_system_config_name UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS public.feature_flags (
    id uuid NOT NULL,
    name character varying NOT NULL,
    config jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    hidden_at timestamp without time zone,
    PRIMARY KEY (id),
    CONSTRAINT unique_feature_flag_name UNIQUE (name)
);
ALTER TABLE IF EXISTS public.roles
ADD FOREIGN KEY (role_group_id) REFERENCES public.role_groups (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.users
ADD FOREIGN KEY (user_group_id) REFERENCES public.user_groups (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
ALTER TABLE IF EXISTS public.users
ADD FOREIGN KEY (role_id) REFERENCES public.roles (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;
END;